version: '3'
services:
    flask:
        image: flask_service
        restart: on-failure
        depends_on:
            - redis
        ports:
            - "9090:3010"

    django:
        image: django_service
        volumes:
            - ./web1:/usr/src/app
        depends_on:
            - redis
            - postgres
        ports:
            - "8888:8000"

    postgres:
        image: postgres_service
        restart: unless-stopped
        expose:
            - "5432"
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: pg_db
        volumes:
            - pgdata:/var/lib/postgresql/data/
            
    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data
        command: redis-server

    nginx:
        image: nginx_service
        restart: on-failure
        ports:
            - "8000:80"
        links:
            - flask

volumes:
  pgdata:
  redisdata:
